### ISSUE TITLE
내장 톰캣 서버에서 첫번째 요청 발생 시 추가적인 딜레이가 생기는 문제

### ISSUE THREAD

**Issue by devwithpug** [devwithpug/RandHand-Chat#23]
## 1. 이슈 내용
> 각각의 REST API, eureka server 에서 첫번째 요청(혹은 1시간 정도 요청이 없는 경우) 발생 시 10~30 초 가량의 딜레이 발생
> 1. EC2 리소스를 확인해보았지만 특별한 문제는 없었음
> 2. 구글링 해본 결과 JVM gc 또는 내장 톰캣과 관련된 이슈로 예상됨

* [https://stackoverflow.com/questions/59242577/why-my-springboot-with-embbeded-tomcat-too-slow-when-process-first-request](https://stackoverflow.com/questions/59242577/why-my-springboot-with-embbeded-tomcat-too-slow-when-process-first-request)

* [https://stackoverflow.com/questions/57312745/slow-first-call-after-restarting-spring-boot-application](https://stackoverflow.com/questions/57312745/slow-first-call-after-restarting-spring-boot-application)

* [https://www.baeldung.com/java-jvm-warmup](https://www.baeldung.com/java-jvm-warmup)

## 2. 작업 할 위치
> `backend/` 

## 3. 작업 목표
> (1) `ApplicationRunner` 추가 하여 해결되는지 확인해보기
> (2) JVM warm up 또는 내장 톰캣 세션 생성 로직 관련 내용들 찾아보기

**Comment by devwithpug** [comment]
* 추가된 설정값

[https://github.com/devwithpug/RandHand-config/blob/main/randhand-prod.yml](https://github.com/devwithpug/RandHand-config/blob/main/randhand-prod.yml)

* eureka server

```yml
eureka:
  server:
    response-cache-update-interval-ms: 10000 # 캐시 업데이트 주기
    peer-node-read-timeout-ms: 400 # 기본 값 200
    peer-node-connect-timeout-ms: 400 # 기본 값 200
```

* eureka client

```yml
logging:
  level:
    com.netflix.discovery.DiscoveryClient: WARN # 불필요한 로그 무시

eureka:
  client:
    registry-fetch-interval-seconds: 15 # 기본 값 30
    disable-delta: true # 유레카 서버 노드 캐시의 변경된 부분만 업데이트
    region: ap-northeast-2 # 서울 리전
```
